# Generated by Django 4.1.7 on 2023-03-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(default=1, upload_to='imagenes/libro/portadas/', verbose_name='Portada del Libro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='sinopsis',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
