# Generated by Django 4.1.7 on 2023-03-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_libro_portada_libro_sinopsis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre del autor')),
                ('apellidos', models.CharField(max_length=80, verbose_name='Apellidos')),
                ('pseudonimo', models.CharField(max_length=100, verbose_name='Pseudónimo')),
                ('nacionalidad', models.CharField(max_length=100, verbose_name='Nacionalidad')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('fechaFallecimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de fallecimiento')),
                ('foto', models.ImageField(upload_to='images/autor/foto', verbose_name='Imagen del autor')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
        migrations.AddField(
            model_name='libro',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='isbn'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='sinopsis',
            field=models.TextField(max_length=500, verbose_name='sinopsis'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='título del libro'),
        ),
    ]
