# Generated by Django 4.1.7 on 2023-03-25 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_editorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.autor', verbose_name='Elija el Autor'),
        ),
        migrations.AddField(
            model_name='libro',
            name='editorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.editorial', verbose_name='Elija la Editorial'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nacionalidad',
            field=models.CharField(choices=[('MX', 'Mexicana'), ('US', 'Estados Unidos'), ('CO', 'Colombia'), ('ES', 'Española'), ('UY', 'Uruguaya')], default='UY', max_length=100, verbose_name='Nacionalidad'),
        ),
    ]
